# Copyright 2017, 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: %DOMAIN_UID%-weblogic-domain-pvc
  namespace: %NAMESPACE%
  labels:
    weblogic.resourceVersion: domain-v1
    weblogic.domainUID: %DOMAIN_UID%
    weblogic.domainName: %DOMAIN_NAME%
spec:
  storageClassName: %DOMAIN_UID%-weblogic-domain-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: %WEBLOGIC_DOMAIN_STORAGE_SIZE%
  selector:
    matchLabels:
      weblogic.resourceVersion: domain-v1
      weblogic.domainUID: %DOMAIN_UID%
      weblogic.domainName: %DOMAIN_NAME%
